name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

env:
  SPARK_VERSION: 3.2
  ZEPPELIN_VERSION : v0.10.1-rc1
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt-get update
      - name: Install prerequisites
        run: |
          sudo apt-get install -f openjdk-8-jdk wget curl git npm libfontconfig r-base-dev -y -q 
      - name: Get Zeppelin sources
        run: git clone --depth 1 -b ${ZEPPELIN_VERSION} https://github.com/apache/zeppelin.git ~/zeppelin
      - run: export MAVEN_OPTS="-Xss64m -Xmx2g -XX:ReservedCodeCacheSize=1g --batch-mode"
      - uses: actions/cache@v1
        with:
          name: cache maven
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build zeppelin from sources
        run: |
          cd ~/zeppelin && \
          mvn clean package -Pbuild-distr -DskipTests -Pscala-2.11 -Pspark-${SPARK_VERSION} -Pspark-scala-2.12
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: ~/zeppelin/zeppelin-distribution/target/zeppelin-0.10.1.tar.gz
