name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

env:
  SPARK_VERSION: 3.2
  ZEPPELIN_VERSION : v0.10.1-rc1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - name: Install prerequisites
        run: |
          sudo apt-get install -f openjdk-8-jdk wget curl git npm libfontconfig r-base-dev r-cran-evaluate  -y -q 
      - name: Get Zeppelin sources
        run: git clone --depth 1 --branch v${ZEPPELIN_VERSION} https://github.com/apache/zeppelin.git ~/zeppelin
      - run: export MAVEN_OPTS="-Xss64m -Xmx2g -XX:ReservedCodeCacheSize=1g"
      - name: Build zeppelin from sources
        run: |
          cd ~/zeppelin && \
          mvn clean package -Pbuild-distr -DskipTests -Pscala-2.11 -Pspark-${SPARK_VERSION} -Pspark-scala-2.12 
